# frontend/Dockerfile
FROM node:18-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Build de l'application pour production
RUN npm run build --prod

# Installation de serveur HTTP simple
RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "4200"]
