FROM node:18-alpine

WORKDIR /app
COPY package*.json ./
COPY . .

RUN npm install
RUN npm install -g serverless

CMD sh -c "sleep 10 && \
           serverless deploy --stage local && \
           node db/seed-data.js"
